### PR TITLE
Adding parser for jsx files

### PR DESCRIPTION
**Pull request by andrefarzat**
A simple parser for `.jsx`

### CODE REVIEW

**Comment by BYK** [comment]
Why not use Babel instead?

**Comment by andrefarzat** [comment]
I could not use Babel for the weird syntax it outputs with the `import` statement. See this example:
screen shot 2015-07-27 at 9 18 14 am
screen shot 2015-07-27 at 9 19 20 am

This `var a = (0, _i18n_._)('something');` is impossible to be caught even using `jsxgettext -k "(0, _i18n_._)`. But using `es6module` and `react` options in acorn, it worked as I expected in the .jsx file

**Comment by BYK** [comment]
Okay, fair enough. That said we already have `require('acorn/util/walk').simple;` in the code so do you think you can use that instead of adding a new dependency? (I'm referring to `jstransform`).

Btw. we may wanna add support for handling the `(0, functionName)("Something")` syntax if that's a thing. I'll look into this separately, thanks for the detective work!

**Comment by andrefarzat** [comment]
So, I could see two possibilities here:
1 - Try using the https://github.com/RReverser/acorn-jsx to be able to walk through the AST ( but this would add `acorn-jsx` as a dependency )
2 - Implement the `(0, functionName)("Something")` syntax if you think this would solve more general problems.

**Comment by BYK** [comment]
I'll tackle the second one separately and I'm not sure that would be the best path for this particular patch since it would introduce Babel as a dependency anyways :)

I like using acorn-jsx becase we already rely on acorn anyways. What do you think?

**Comment by andrefarzat** [comment]
Between Babel and acron-jsx, I like acron-jsx better too. I will start making tests with acron-jsx and update this PR, unless you're already on it =)

**Comment by BYK** [comment]
Sounds great!

>unless you're already on it =)

No I'm not, I'm lazy :P

**Comment by andrefarzat** [comment]
I am still having fun with acorn-jsx. I will close this PR, for it's pointless now.

**Pull request closed without merging**
